### ISSUE TITLE
Set, nu HashSet

### ISSUE THREAD

**Issue by stefanbulzan** [AdrianBuzamat/curs10-homework#4]
https://github.com/AdrianBuzamat/curs10-homework/blob/9513218111fc7fbd4f0efc9a7e6494dbfd61cb30/src/ro/fasttrackit/curs10/ex2/Buqet.java#L8

**Comment by AdrianBuzamat** [comment]
Am inteles de ce nu pot folosi implementarea, ci mereu interfata. Daca folosesc Set in cazul asta, nu mai am metodele disponibile.
